version: "3"

services:

  db:
    image: mariadb:10.6
    container_name: mariadb
    networks:
      frappe_network: null
    healthcheck:
      test: mysqladmin ping -h localhost --password=admin
      interval: 1s
      retries: 15
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

  redis-queue:
    image: redis:6.2-alpine
    container_name: redis_queue
    networks:
      frappe_network: null
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-queue-data:/data

  redis-cache:
    image: redis:6.2-alpine
    container_name: redis_cache
    networks:
      frappe_network: null
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-cache-data:/data

volumes:
  db-data:
  redis-queue-data:
  redis-cache-data:
networks:
  frappe_network:
    external: true